baseURL = "https://stevenmurawski.com/"
theme = "ghostwriter"
disablePathToLower = true
title = "A Sysadmin, An SRE, and a DevOps Walk Into a Bar"
languageCode = "en-us"
metaDataFormat = "toml"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License"
rssLimit = 10
relativeURLs = false
googleAnalytics = "UA-36317457-1"
disqusShortname = "stevenmurawski"

[permalinks]
post = "/:year/:month/:filename/"

[params]
github = "https://github.com/smurawski"
linkedin = "https://linkedin.com/in/usepowershell"
twitter = "https://twitter.com/stevenmurawski"
stackoverflow = "https://stackoverflow.com/users/1233/steven-murawski"
shareTwitter = true
shareFacebook = true
shareGooglePlus = true
shareLinkedIn = true

[author]
name = "Steven Murawski"
email = "steven.murawski@gmail.com"

[[menu.main]]
name = "About"
url = "/page/about"
weight = 1

[[menu.main]]
name = "Blog"
url = "/"
weight = 2

[[menu.main]]
name = "DevOps Reading List"
url = "/page/devops-reading-list"
weight = 3
